markdown: kramdown

# Setup
title:            Mirin Template
tagline:          'A NotITG Template'
description:      'A <a href="https://notitg.heysora.net" target="_blank">NotITG</a> template that features a powerful ease system. Made by <a href="https://github.com/XeroOl">XeroOl</a>.'
url:              http://xerool.github.io
baseurl:          /hyde

collections:
  docs:
    output: true
    permalink: /docs/:title/
  posts:
    output: true
    permalink: /posts/:title/

author:
  name:           'XeroOl'
  url:            www.github.com/XeroOl

# Custom vars
version:          5.0.0

github:
  repo:           https://github.com/XeroOl/notitg-mirin
discord:
  url:            https://discord.gg/wHTFcHdkyg
